import type { ActionStep } from "../../../../../shared/types";
import type { StepFieldDefinition } from "../../types";

export const integrationStepFields: Record<string, StepFieldDefinition[]> = {
  apiRequest: [
    {
      key: "method",
      label: "Method",
      type: "select",
      options: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
      hint: "HTTP verb",
      example: "POST",
    },
    {
      key: "url",
      label: "URL",
      type: "string",
      supportsInterpolation: true,
      hint: "Request URL — supports context interpolation",
      example: "https://api.example.com/users/{{context.userId}}",
    },
    {
      key: "params",
      label: "Params",
      type: "object",
      hint: "Query-string parameters appended to the URL",
      example: "page: 1",
    },
    {
      key: "headers",
      label: "Headers",
      type: "object",
      hint: "HTTP request headers",
      example: "Authorization: Bearer {{context.token}}",
    },
    {
      key: "auth",
      label: "Auth",
      type: "object",
      hint: "Basic-auth credentials — use keys username and password",
      example: "username: admin",
    },
    {
      key: "body",
      label: "Body (JSON)",
      type: "json",
      hint: "Request body sent as JSON",
      example: '{ "name": "Alice" }',
      visibleWhen: (step: ActionStep) => {
        const method = (typeof step.method === "string" ? (step.method as string) : "GET").toUpperCase();
        return !["GET", "HEAD", "OPTIONS"].includes(method);
      },
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the response — shape: { status, headers, body }",
      example: "apiResponse",
    },
    {
      key: "timeout",
      label: "Timeout (ms)",
      type: "number",
      hint: "Max time to wait for a response, in milliseconds",
      example: "10000",
    },
    {
      key: "ignoreHttpErrors",
      label: "Ignore HTTP errors",
      type: "boolean",
      hint: "Continue execution even if the response status is 4xx or 5xx",
    },
  ],
  setVariable: [
    {
      key: "source",
      label: "Source",
      type: "string",
      supportsInterpolation: true,
      hint: "Value to store — supports context interpolation",
      example: "{{context.apiResponse.body.token}}",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the value under",
      example: "authToken",
    },
  ],
  shell: [
    {
      key: "command",
      label: "Command",
      type: "string",
      supportsInterpolation: true,
      hint: "Shell command to run",
      example: "git status",
      visibleWhen: (step: ActionStep) => step.commands === undefined,
    },
    {
      key: "commands",
      label: "Commands",
      type: "stringArray",
      supportsInterpolation: true,
      hint: "List of shell commands run in sequence",
      example: "git fetch",
      visibleWhen: (step: ActionStep) => step.commands !== undefined,
    },
    {
      key: "shellArgs",
      label: "Shell args",
      type: "stringArray",
      hint: "Extra arguments passed to the shell binary (e.g. PowerShell flags)",
      example: "-ExecutionPolicy Bypass",
    },
    {
      key: "cwd",
      label: "Working directory",
      type: "string",
      supportsInterpolation: true,
      hint: "Directory from which the command is run",
      example: "C:\\my-project",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the result — shape: { stdout, stderr, exitCode }",
      example: "shellResult",
    },
    {
      key: "timeout",
      label: "Timeout (ms)",
      type: "number",
      hint: "Max time allowed for the command to finish, in milliseconds",
      example: "30000",
    },
  ],
  getArguments: [
    {
      key: "required",
      label: "Required args",
      type: "stringArray",
      hint: "Argument names that must be provided when invoking this action",
      example: "username",
    },
    {
      key: "optional",
      label: "Optional args",
      type: "stringArray",
      hint: "Argument names that may be omitted — use defaults to set fallback values",
      example: "retries",
    },
    {
      key: "defaults",
      label: "Defaults",
      type: "object",
      hint: "Fallback values for optional arguments",
      example: "retries: 3",
    },
  ],
  invokeAction: [
    {
      key: "name",
      label: "Action name",
      type: "string",
      hint: "Name of the action to run as a sub-routine",
      example: "loginAction",
    },
    {
      key: "args",
      label: "Args",
      type: "object",
      hint: "Arguments passed to the invoked action — supports context interpolation in values",
      example: "username: {{context.user}}",
    },
    {
      key: "continueOnError",
      label: "Continue on error",
      type: "boolean",
      hint: "Keep running the parent action even if this invocation fails",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the invoked action's return value",
      example: "loginResult",
    },
  ],
  writeFile: [
    {
      key: "path",
      label: "Path",
      type: "string",
      supportsInterpolation: true,
      hint: "Absolute path of the file to write",
      example: "C:\\output\\report.txt",
    },
    {
      key: "content",
      label: "Content",
      type: "string",
      supportsInterpolation: true,
      hint: "Text content to write — supports context interpolation",
      example: "Hello {{context.name}}",
    },
    {
      key: "backupIfExists",
      label: "Backup if exists",
      type: "boolean",
      hint: "Rename the existing file with a timestamp suffix before overwriting",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the written file path",
      example: "reportPath",
    },
  ],
};
