"use strict";

/**
 * Role: Resolves template placeholders inside step definitions before execution.
 * Not in this file: Step validation and step execution orchestration.
 * Key dependencies: process.env and runtime context generated by action-runner.
 * See also: action-runner/runSteps.js, action-runner/normalizeSteps.js
 */

const TEMPLATE_REGEX = /\{\{\s*(context|env)\.([^}]+)\s*\}\}/g;

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function getValueByPath(source, pathExpression) {
  const pathParts = pathExpression
    .split(".")
    .map((pathPart) => pathPart.trim())
    .filter((pathPart) => pathPart.length > 0);

  return pathParts.reduce((currentValue, currentPathPart) => {
    if (currentValue === undefined || currentValue === null) {
      return undefined;
    }

    return currentValue[currentPathPart];
  }, source);
}

function resolveTemplateValue(scopeName, expressionPath, runtimeContext) {
  if (scopeName === "env") {
    return process.env[expressionPath];
  }

  return getValueByPath(runtimeContext, expressionPath);
}

function interpolateString(value, runtimeContext) {
  const templateMatches = Array.from(value.matchAll(TEMPLATE_REGEX));

  if (templateMatches.length === 0) {
    return value;
  }

  if (templateMatches.length === 1 && templateMatches[0][0] === value) {
    const [, scopeName, expressionPath] = templateMatches[0];
    const trimmedPath = expressionPath.trim();
    const resolvedValue = resolveTemplateValue(scopeName, trimmedPath, runtimeContext);

    if (resolvedValue === undefined || resolvedValue === null) {
      throw new Error(
        `[Action Runner] variable "{{${scopeName}.${trimmedPath}}}" has no value`
      );
    }

    return resolvedValue;
  }

  return value.replace(TEMPLATE_REGEX, (_fullMatch, scopeName, expressionPath) => {
    const trimmedPath = expressionPath.trim();
    const resolvedValue = resolveTemplateValue(scopeName, trimmedPath, runtimeContext);

    if (resolvedValue === undefined || resolvedValue === null) {
      throw new Error(
        `[Action Runner] variable "{{${scopeName}.${trimmedPath}}}" has no value`
      );
    }

    if (typeof resolvedValue === "object") {
      return JSON.stringify(resolvedValue);
    }

    return String(resolvedValue);
  });
}

function interpolateValue(value, runtimeContext) {
  if (typeof value === "string") {
    return interpolateString(value, runtimeContext);
  }

  if (Array.isArray(value)) {
    return value.map((arrayItem) => interpolateValue(arrayItem, runtimeContext));
  }

  if (isObject(value)) {
    return Object.entries(value).reduce((accumulator, [key, objectValue]) => {
      accumulator[key] = interpolateValue(objectValue, runtimeContext);
      return accumulator;
    }, {});
  }

  return value;
}

function interpolateStep(step, runtimeContext) {
  return interpolateValue(step, runtimeContext);
}

module.exports = {
  interpolateStep,
};
