export const IPC_CHANNELS = {
  configRead: "config:read",
  configWrite: "config:write",
  profileStatus: "profile:status",
  profileRegenerate: "profile:regenerate",
  profileOpenFolder: "profile:openFolder",
  scheduledTasksList: "scheduledTasks:list",
  scheduledTasksSave: "scheduledTasks:save",
  scheduledTasksDelete: "scheduledTasks:delete",
  scheduledTasksToggle: "scheduledTasks:toggle",
  customActionsRun: "customActions:run",
  browserProfilesList: "browserProfiles:list",
  themeSet: "theme:set",
  localeSync: "locale:sync",
  localeGet: "locale:get",
  localeChanged: "locale:changed",
  appNewCustomAction: "app:newCustomAction",
  appNewScheduledTask: "app:newScheduledTask",
} as const;
