import type { ActionStep } from "../../../shared/types";
import type { StepFieldDefinition } from "./types";

export const SUPPORTED_ACTION_TYPES = [
  "navigate",
  "type",
  "click",
  "wait",
  "waitForPageState",
  "setWebStorage",
  "closeBrowser",
  "forEachElement",
  "forEach",
  "apiRequest",
  "setVariable",
  "shell",
  "getArguments",
  "invokeAction",
  "tryCatch",
  "ifElse",
  "writeFile",
];

export const BROWSER_STEP_ACTIONS = [
  "navigate",
  "type",
  "click",
  "waitForPageState",
  "setWebStorage",
  "closeBrowser",
  "forEachElement",
] as const;

export const BROWSER_STEP_ACTION_SET = new Set<string>(BROWSER_STEP_ACTIONS);

export const STEP_FIELD_DEFINITIONS: Record<string, StepFieldDefinition[]> = {
  navigate: [
    {
      key: "url",
      label: "URL",
      type: "string",
      supportsInterpolation: true,
      hint: "Full URL to navigate to",
      example: "https://example.com/login",
    },
    {
      key: "waitForLoading",
      label: "Wait for loading",
      type: "boolean",
      hint: "Wait for loading overlays to disappear before continuing",
    },
  ],
  type: [
    {
      key: "selector",
      label: "Selector",
      type: "string",
      hint: "CSS selector for the input element to type into",
      example: "#username",
    },
    {
      key: "value",
      label: "Value",
      type: "string",
      supportsInterpolation: true,
      hint: "Text to type — supports context interpolation",
      example: "{{context.username}}",
    },
    {
      key: "delay",
      label: "Delay",
      type: "number",
      hint: "Milliseconds between each keystroke",
      example: "50",
    },
    {
      key: "iframe",
      label: "IFrame selector",
      type: "string",
      hint: "CSS selector for the iframe that contains the target element",
      example: "iframe#content-frame",
    },
  ],
  click: [
    {
      key: "selector",
      label: "Selector",
      type: "string",
      hint: "CSS selector for the element to click",
      example: "button.submit",
    },
    {
      key: "waitForSelector",
      label: "Wait for selector",
      type: "string",
      hint: "Wait until this selector is visible before clicking",
      example: ".modal-confirm",
    },
    {
      key: "waitForNavigation",
      label: "Wait for navigation",
      type: "boolean",
      hint: "Wait for the page to navigate after the click",
    },
    {
      key: "waitForLoading",
      label: "Wait for loading",
      type: "boolean",
      hint: "Wait for loading overlays to disappear after the click",
    },
    {
      key: "timeout",
      label: "Timeout (ms)",
      type: "number",
      hint: "Max time to wait for the selector, in milliseconds",
      example: "5000",
    },
    {
      key: "iframe",
      label: "IFrame selector",
      type: "string",
      hint: "CSS selector for the iframe that contains the target element",
      example: "iframe#content-frame",
    },
    {
      key: "jsClick",
      label: "Use JS click",
      type: "boolean",
      hint: "Trigger the click via JavaScript instead of a simulated mouse event — useful for elements blocked by overlays",
    },
  ],
  wait: [
    {
      key: "ms",
      label: "Milliseconds",
      type: "number",
      hint: "How long to pause execution",
      example: "2000",
    },
  ],
  waitForPageState: [
    {
      key: "selector",
      label: "Selector",
      type: "string",
      hint: "Wait until this element is visible on the page",
      example: ".dashboard-header",
    },
    {
      key: "urlContains",
      label: "URL contains",
      type: "string",
      supportsInterpolation: true,
      hint: "Wait until the current URL contains this substring",
      example: "/dashboard",
    },
    {
      key: "waitForLoading",
      label: "Wait for loading",
      type: "boolean",
      hint: "Wait for loading overlays to disappear before continuing",
    },
    {
      key: "timeout",
      label: "Timeout (ms)",
      type: "number",
      hint: "Max time to wait for the condition, in milliseconds",
      example: "10000",
    },
    {
      key: "iframe",
      label: "IFrame selector",
      type: "string",
      hint: "CSS selector for the iframe to search within",
      example: "iframe#content-frame",
      visibleWhen: (step: ActionStep) =>
        typeof step.selector === "string" && (step.selector as string).length > 0,
    },
  ],
  setWebStorage: [
    {
      key: "localStorage",
      label: "Local storage",
      type: "object",
      hint: "Key-value pairs to write into localStorage",
      example: "token: abc123",
    },
    {
      key: "sessionStorage",
      label: "Session storage",
      type: "object",
      hint: "Key-value pairs to write into sessionStorage",
      example: "sessionId: xyz",
    },
    {
      key: "cookies",
      label: "Cookies (JSON array)",
      type: "json",
      hint: "Array of cookie objects accepted by Puppeteer's setCookie",
      example: '[{ "name": "token", "value": "abc", "domain": ".example.com" }]',
    },
  ],
  closeBrowser: [],
  forEachElement: [
    {
      key: "selector",
      label: "Selector",
      type: "string",
      hint: "CSS selector for the set of elements to iterate over",
      example: ".product-row",
    },
    {
      key: "textContentSelector",
      label: "Text content selector",
      type: "string",
      hint: "Within each matched element, read text from this sub-selector",
      example: ".product-name",
    },
    {
      key: "excludeTextPatterns",
      label: "Exclude text patterns",
      type: "stringArray",
      hint: "Skip elements whose text matches any of these substrings",
      example: "Loading...",
    },
    {
      key: "clickSelector",
      label: "Click selector",
      type: "string",
      hint: "Within each matched element, click this sub-selector",
      example: "button.details",
    },
    {
      key: "skipIfPositionMatch",
      label: "Skip position match",
      type: "object",
      hint: "Skip an element if its bounding-box position matches this object",
    },
  ],
  forEach: [
    {
      key: "list",
      label: "List (JSON array)",
      type: "json",
      supportsInterpolation: true,
      hint: "JSON array to iterate over — each item is available as {{context.item}}",
      example: '["apple", "banana", "cherry"]',
      visibleWhen: (step: ActionStep) => step.count === undefined,
    },
    {
      key: "count",
      label: "Count",
      type: "number",
      hint: "Number of times to repeat the sub-steps",
      example: "5",
      visibleWhen: (step: ActionStep) => step.count !== undefined,
    },
  ],
  apiRequest: [
    {
      key: "method",
      label: "Method",
      type: "select",
      options: ["GET", "POST", "PATCH", "PUT", "DELETE"],
      hint: "HTTP verb",
      example: "POST",
    },
    {
      key: "url",
      label: "URL",
      type: "string",
      supportsInterpolation: true,
      hint: "Request URL — supports context interpolation",
      example: "https://api.example.com/users/{{context.userId}}",
    },
    {
      key: "params",
      label: "Params",
      type: "object",
      hint: "Query-string parameters appended to the URL",
      example: "page: 1",
    },
    {
      key: "headers",
      label: "Headers",
      type: "object",
      hint: "HTTP request headers",
      example: "Authorization: Bearer {{context.token}}",
    },
    {
      key: "auth",
      label: "Auth",
      type: "object",
      hint: "Basic-auth credentials — use keys username and password",
      example: "username: admin",
    },
    {
      key: "body",
      label: "Body (JSON)",
      type: "json",
      hint: "Request body sent as JSON",
      example: '{ "name": "Alice" }',
      visibleWhen: (step: ActionStep) => {
        const method = (typeof step.method === "string" ? (step.method as string) : "GET").toUpperCase();
        return method !== "GET" && method !== "HEAD";
      },
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the response — shape: { status, headers, body }",
      example: "apiResponse",
    },
    {
      key: "timeout",
      label: "Timeout (ms)",
      type: "number",
      hint: "Max time to wait for a response, in milliseconds",
      example: "10000",
    },
    {
      key: "ignoreHttpErrors",
      label: "Ignore HTTP errors",
      type: "boolean",
      hint: "Continue execution even if the response status is 4xx or 5xx",
    },
  ],
  setVariable: [
    {
      key: "source",
      label: "Source",
      type: "string",
      supportsInterpolation: true,
      hint: "Value to store — supports context interpolation",
      example: "{{context.apiResponse.body.token}}",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the value under",
      example: "authToken",
    },
  ],
  shell: [
    {
      key: "command",
      label: "Command",
      type: "string",
      supportsInterpolation: true,
      hint: "Shell command to run",
      example: "git status",
      visibleWhen: (step: ActionStep) => step.commands === undefined,
    },
    {
      key: "commands",
      label: "Commands",
      type: "stringArray",
      supportsInterpolation: true,
      hint: "List of shell commands run in sequence",
      example: "git fetch",
      visibleWhen: (step: ActionStep) => step.commands !== undefined,
    },
    {
      key: "shellArgs",
      label: "Shell args",
      type: "stringArray",
      hint: "Extra arguments passed to the shell binary (e.g. PowerShell flags)",
      example: "-ExecutionPolicy Bypass",
    },
    {
      key: "cwd",
      label: "Working directory",
      type: "string",
      supportsInterpolation: true,
      hint: "Directory from which the command is run",
      example: "C:\\my-project",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the result — shape: { stdout, stderr, exitCode }",
      example: "shellResult",
    },
    {
      key: "timeout",
      label: "Timeout (ms)",
      type: "number",
      hint: "Max time allowed for the command to finish, in milliseconds",
      example: "30000",
    },
  ],
  getArguments: [
    {
      key: "required",
      label: "Required args",
      type: "stringArray",
      hint: "Argument names that must be provided when invoking this action",
      example: "username",
    },
    {
      key: "optional",
      label: "Optional args",
      type: "stringArray",
      hint: "Argument names that may be omitted — use defaults to set fallback values",
      example: "retries",
    },
    {
      key: "defaults",
      label: "Defaults",
      type: "object",
      hint: "Fallback values for optional arguments",
      example: "retries: 3",
    },
  ],
  invokeAction: [
    {
      key: "name",
      label: "Action name",
      type: "string",
      hint: "Name of the action to run as a sub-routine",
      example: "loginAction",
    },
    {
      key: "args",
      label: "Args",
      type: "object",
      hint: "Arguments passed to the invoked action — supports context interpolation in values",
      example: "username: {{context.user}}",
    },
    {
      key: "continueOnError",
      label: "Continue on error",
      type: "boolean",
      hint: "Keep running the parent action even if this invocation fails",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the invoked action's return value",
      example: "loginResult",
    },
  ],
  tryCatch: [],
  ifElse: [],
  writeFile: [
    {
      key: "path",
      label: "Path",
      type: "string",
      supportsInterpolation: true,
      hint: "Absolute path of the file to write",
      example: "C:\\output\\report.txt",
    },
    {
      key: "content",
      label: "Content",
      type: "string",
      supportsInterpolation: true,
      hint: "Text content to write — supports context interpolation",
      example: "Hello {{context.name}}",
    },
    {
      key: "backupIfExists",
      label: "Backup if exists",
      type: "boolean",
      hint: "Rename the existing file with a timestamp suffix before overwriting",
    },
    {
      key: "storeAs",
      label: "Store as",
      type: "string",
      hint: "Variable name to store the written file path",
      example: "reportPath",
    },
  ],
};
