import { defineConfig } from "vitest/config";

const coverageExclude = [
  "src/**/*.test.*",
  "src/**/*.node.test.*",
  "src/**/*.integration.test.*",
  "src/test/**",
  "src/**/types.ts",
  "src/renderer/assets/**",
  "src/main/index.ts",
  "src/preload/index.ts",
  "src/renderer/main.tsx",
  // Thin IPC handlers covered indirectly via services
  "src/main/ipc/config.ts",
  "src/main/ipc/customActions.ts",
  "src/main/ipc/profile.ts",
  "src/main/ipc/scheduledTasks.ts",
  "src/main/ipc/theme.ts",
  "src/main/ipc/browserProfiles.ts",
  "src/main/windowIconPath.ts",
  // Services without direct unit coverage yet
  "src/main/services/profileBlock.ts",
  "src/main/services/profileHealth.ts",
  "src/main/services/profilePath.ts",
  "src/main/services/repoPaths.ts",
  "src/main/services/ps1Parser.ts",
  // Service I/O modules covered by dedicated tests; branch-heavy Electron/fs paths
  "src/main/services/scheduledTasksService.ts",
  "src/main/services/packagedDataBootstrap.ts",
  "src/main/services/configService.ts",
  "src/main/services/browserProfilesService.ts",
  "src/main/services/profileBlockCore.ts",
  // UI orchestration hooks and visual flow builders tested via integration/manual
  "src/renderer/utils/**",
  "src/renderer/hooks/useFloatingDropdownPosition.ts",
  "src/renderer/tabs/custom-actions/hooks/useActionEditor.ts",
  "src/renderer/tabs/custom-actions/hooks/useActionRows.ts",
  "src/renderer/tabs/custom-actions/hooks/useEditorLifecycle.ts",
  "src/renderer/tabs/custom-actions/hooks/useEditorPersistence.ts",
  "src/renderer/tabs/custom-actions/hooks/useEditorValidation.ts",
  "src/renderer/tabs/custom-actions/hooks/useFlowEditorViewport.ts",
  "src/renderer/tabs/custom-actions/hooks/useRunActionModal.ts",
  "src/renderer/tabs/custom-actions/utils/buildBlockFlow.ts",
  "src/renderer/tabs/custom-actions/utils/flow.ts",
  "src/renderer/tabs/custom-actions/utils/flowLayout.ts",
  "src/renderer/tabs/custom-actions/utils/flowShiftScrollPan.ts",
  "src/renderer/tabs/custom-actions/utils/flowScope.ts",
  "src/renderer/tabs/custom-actions/utils/flowViewportFocus.ts",
  "src/renderer/tabs/custom-actions/utils/actionConfigUtils.ts",
  "src/renderer/tabs/scheduled-tasks/utils/scheduledTaskCommandDraft.ts",
];

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "src/**/*.test.ts",
      "src/**/*.test.tsx",
      "src/**/*.node.test.ts",
      "src/**/*.integration.test.ts",
    ],
    setupFiles: ["src/test/setup.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/shared/**/*.ts",
        "src/main/**/*.ts",
        "src/renderer/**/utils/**/*.ts",
        "src/renderer/hooks/**/*.ts",
        "src/renderer/theme/**/*.ts",
        "src/renderer/context/**/*.tsx",
        "src/renderer/i18n/**/*.tsx",
        "src/renderer/tabs/**/constants/**/*.ts",
        "src/renderer/tabs/predefined-commands/**/*.ts",
        "src/renderer/tabs/scheduled-tasks/utils/**/*.ts",
        "src/renderer/tabs/scheduled-tasks/constants.ts",
        "src/renderer/tabs/custom-actions/hooks/**/*.ts",
      ],
      exclude: coverageExclude,
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
  },
});
